#! /bin/bash
echo "hello bash script"
echo "Eagles don't hang out with chickens"
echo "We are wandarer's in the darkness"
echo "The more you sweat in practice , The less you bleed in the battle"
echo "Fuck Society"
echo "When your fucked don't show that you are fucked that makes other person fucked"
echo "Born to die, so learn the art of dying!"
echo "You are fucked already then when are you involving me bitch, please get lost!"
echo "I love none except you mom, You are the love of my life you have the heaven under your feet"
echo "Believe in God It makes you even stronger and not alone vibe"
echo "Don't be afraid of doing what you wanna do"
echo "Love unconditonally :) I'll protect you no matter what"
echo "What you give out, it brings more than that in - Karma's rule"
echo "Surround yourself with people who are ruthlessly devoted to becoming thier greatest selves"
echo "Stay away bitch, I have lot to do in my life with my boyfriend"
echo "Devils are'nt born , they are made by the reasons"
echo "Love is bitch so be rich to handle that shit
